name: flutter_persian_date_picker
description: DatePicker with full support of the Persian calendar with highly customizable and responsive UI.
version: 0.0.1
homepage: https://github.com/arminyazdian/flutter-persian-date-picker

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shamsi_date: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: